export const FETCH_COUNTRY_PENDING = 'FETCH_COUNTRY_PENDING';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_ERROR = 'FETCH_COUNTRY_ERROR';
export const FILTERED_COUNTRIES = 'FILTERED_COUNTRIES';
export const RESET_FILTERED_COUNTRIES = 'RESET_FILTERED_COUNTRIES';
